# Generated by Django 3.2.6 on 2021-08-28 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flower_name', models.CharField(max_length=20)),
                ('flower_color', models.CharField(max_length=20)),
                ('added_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
